name: Diagnostic Pronote
on:
  push:
    branches: [diag-pronote-page]
permissions:
  contents: read
jobs:
  sonde:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run -A --config deno.json sonde.ts
        working-directory: diag
